export const serviceData = [
  {
    id: 1,
    name: "Tỉa lông",
    type: "Spa",
    description: "Dịch vụ tỉa lông cho thú cưng.",
    price: 30,
  },
  {
    id: 2,
    name: "Tắm rửa",
    type: "Spa",
    description: "Dịch vụ tắm rửa cho thú cưng.",
    price: 25,
  },
  {
    id: 3,
    name: "Massage",
    type: "Spa",
    description: "Dịch vụ massage cho thú cưng.",
    price: 40,
  },
  {
    id: 4,
    name: "Manicure và Pedicure",
    type: "Spa",
    description: "Dịch vụ manicure và pedicure cho thú cưng.",
    price: 35,
  },
  {
    id: 5,
    name: "Nhuộm lông",
    type: "Spa",
    description: "Dịch vụ nhuộm lông cho thú cưng.",
    price: 50,
  },
  {
    id: 6,
    name: "Khóa học cơ bản",
    type: "Huấn luyện",
    description: "Khóa học huấn luyện cơ bản cho thú cưng.",
    price: 50,
  },
  {
    id: 7,
    name: "Khóa học nâng cao",
    type: "Huấn luyện",
    description: "Khóa học huấn luyện nâng cao cho thú cưng.",
    price: 75,
  },
  {
    id: 8,
    name: "Khóa học chó sủa",
    type: "Huấn luyện",
    description: "Khóa học huấn luyện cho thú cưng sủa nhiều.",
    price: 60,
  },
  {
    id: 9,
    name: "Khóa học chó con",
    type: "Huấn luyện",
    description: "Khóa học huấn luyện cho chó con.",
    price: 45,
  },
  {
    id: 10,
    name: "Khóa học chó lớn",
    type: "Huấn luyện",
    description: "Khóa học huấn luyện cho chó lớn.",
    price: 70,
  },
  {
    id: 11,
    name: "Kiểm tra sức khỏe định kỳ",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Kiểm tra sức khỏe định kỳ cho thú cưng.",
    price: 40,
  },
  {
    id: 12,
    name: "Chăm sóc y tế",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ chăm sóc y tế cho thú cưng.",
    price: 60,
  },
  {
    id: 13,
    name: "Phòng ngừa bệnh",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ phòng ngừa bệnh cho thú cưng.",
    price: 55,
  },
  {
    id: 14,
    name: "Tiêm phòng",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ tiêm phòng cho thú cưng.",
    price: 45,
  },
  {
    id: 15,
    name: "Xét nghiệm máu",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ xét nghiệm máu cho thú cưng.",
    price: 65,
  },
  {
    id: 16,
    name: "Phòng ngừa bệnh",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ phòng ngừa bệnh cho thú cưng.",
    price: 55,
  },
  {
    id: 17,
    name: "Tiêm phòng",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ tiêm phòng cho thú cưng.",
    price: 45,
  },
  {
    id: 18,
    name: "Xét nghiệm máu",
    type: "Chăm sóc sức khỏe thú cưng",
    description: "Dịch vụ xét nghiệm máu cho thú cưng.",
    price: 65,
  },
];
export default serviceData;
