export const petData = [
  {
    id: 1,
    name: "Apollo",
    age: 2,
    breed: "Golden Retriever",
    description: "Thân thiện và năng động, thích chơi fetch.",
    gender: "Đực",
    image: "https://images.pexels.com/photos/4587987/pexels-photo-4587987.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 2,
    name: "Gretchen",
    age: 1,
    breed: "Poodle",
    description: "Dễ dị ứng và nghịch ngợm, thích được chải chuốt.",
    gender: "Cái",
    image: "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    name: "Pepper",
    age: 2,
    breed: "Mèo ba tư",
    description: "Độc lập và đáng yêu, thích nằm lang thang.",
    gender: "Đực",
    image: "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    name: "Daisy",
    age: 2,
    breed: "Bulldog",
    description: "Trung thành và hiền lành, tốt với trẻ em.",
    gender: "Cái",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 5,
    name: "Max",
    age: 4,
    breed: "German Shepherd",
    description: "Thông minh và bảo vệ, thú cưng bảo vệ xuất sắc.",
    gender: "Đực",
    image: "https://images.pexels.com/photos/1495548/pexels-photo-1495548.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 6,
    name: "Lucy",
    age: 2,
    breed: "Dachshund",
    description: "Tò mò và nghịch ngợm, thích đào hang.",
    gender: "Cái",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 7,
    name: "Rocky",
    age: 3,
    breed: "Boxer",
    description: "Sống động và đáng yêu, tốt với gia đình.",
    gender: "Đực",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 8,
    name: "Luna",
    age: 2,
    breed: "Husky",
    description: "Thích phiêu lưu và độc lập, thích thiên nhiên.",
    gender: "Cái",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 9,
    name: "Teddy",
    age: 1,
    breed: "Cavalier King Charles Spaniel",
    description: "Thân thiện và đáng yêu, một chú chó đặt lòng.",
    gender: "Đực",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 10,
    name: "Molly",
    age: 3,
    breed: "Yorkshire Terrier",
    description: "Năng lượng và nhỏ nhắn, một người bạn tuyệt vời.",
    gender: "Cái",
    image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 11,
    name: "Con báo",
    age: 2,
    breed: "Gâu đần",
    description: "Con báo, quậy banh nhà, thích ke đầu, lộn mèo",
    gender: "Đực",
    image: "https://sohanews.sohacdn.com/thumb_w/1000/160588918557773824/2023/8/8/photo-5-1691492506862761842416.jpg",
  },
  {
    id: 12,
    name: "Con báo",
    age: 2,
    breed: "Gâu đần",
    description: "Con báo, quậy banh nhà, thích ke đầu, lộn mèo",
    gender: "Đực",
    image: "https://sohanews.sohacdn.com/thumb_w/1000/160588918557773824/2023/8/8/photo-5-1691492506862761842416.jpg",
  },
  {
    id: 13,
    name: "Con báo",
    age: 2,
    breed: "Gâu đần",
    description: "Con báo, quậy banh nhà, thích ke đầu, lộn mèo",
    gender: "Đực",
    image: "https://sohanews.sohacdn.com/thumb_w/1000/160588918557773824/2023/8/8/photo-5-1691492506862761842416.jpg",
  },
  {
    id: 14,
    name: "mèo méo meo mèo meo",
    age: 2,
    breed: "Con mèo ngu ngốc",
    description: "Đáng iu, cute hột me, phô mai que",
    gender: "Đực",
    image: "https://nguoinoitieng.tv/images/nnt/97/0/bb39.jpg",
  },
];
