export const petData = [
    {
      id: 1,
      name: "Apollo",
      age: 2,
      breed: "Golden Retriever",
      description: "Friendly and active, loves to play fetch.",
      gender: "Male",
      image: "https://images.pexels.com/photos/4587987/pexels-photo-4587987.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2,
      name: "Gretchen",
      age: 1,
      breed: "Poodle",
      description: "Hypoallergenic and playful, enjoys being groomed.",
      gender: "Female",
      image: "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
      id: 3,
      name: "Pepper",
      age: 2,
      breed: "Mèo ba tư",
      description: "Independent and affectionate, enjoys lounging around.",
      gender: "Male",
      image: "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
      id: 4,
      name: "Daisy",
      age: 2,
      breed: "Bulldog",
      description: "Loyal and gentle, great with kids.",
      gender: "Female",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 5,
      name: "Max",
      age: 4,
      breed: "German Shepherd",
      description: "Intelligent and protective, an excellent guard dog.",
      gender: "Male",
      image: "https://images.pexels.com/photos/1495548/pexels-photo-1495548.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 6,
      name: "Lucy",
      age: 2,
      breed: "Dachshund",
      description: "Curious and playful, loves to dig.",
      gender: "Female",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 7,
      name: "Rocky",
      age: 3,
      breed: "Boxer",
      description: "Lively and affectionate, great with families.",
      gender: "Male",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 8,
      name: "Luna",
      age: 2,
      breed: "Husky",
      description: "Adventurous and independent, enjoys the outdoors.",
      gender: "Female",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 9,
      name: "Teddy",
      age: 1,
      breed: "Cavalier King Charles Spaniel",
      description: "Friendly and affectionate, a lap dog.",
      gender: "Male",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 10,
      name: "Molly",
      age: 3,
      breed: "Yorkshire Terrier",
      description: "Energetic and small, a great companion.",
      gender: "Female",
      image: "https://images.pexels.com/photos/220938/pexels-photo-220938.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  